version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "python:latest"
    steps:
      - checkout
      - run: python3 add.py


workflows:
  build_and_push_image:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          account-url: 877149297530.dkr.ecr.us-east-1.amazonaws.com
          aws-access-key-id: AKIA4YORMDN5FPBE2AV2
          aws-secret-access-key: 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
          dockerfile: Dockerfile
          path: .
          region: us-east-1
          repo: circle_pushimage
          requires:
            - test
      

