version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "python:latest"
    steps:
      - checkout
      - run: python3 add.py


workflows:
  build_and_push_image:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION_ENV_VAR_NAME
          repo: circle_pushimage
          requires:
            - test
      

#start